# Generated by Django 5.2 on 2025-04-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('grupo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
            ],
            options={
                'db_table': 'grupo_articulo',
                'ordering': ['codigo_grupo'],
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('linea_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_linea', to='core.grupoarticulo')),
            ],
            options={
                'db_table': 'linea_articulo',
                'ordering': ['codigo_linea'],
            },
        ),
    ]
