# Generated by Django 5.2 on 2025-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoarticulo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1),
        ),
        migrations.AlterField(
            model_name='lineaarticulo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1),
        ),
    ]
