# Generated by Django 5.2 on 2025-04-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_grupoarticulo_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('codigo_barras', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('imagen', models.CharField(max_length=250, null=True)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_grupo', to='core.grupoarticulo')),
                ('linea_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_linea', to='core.lineaarticulo')),
            ],
            options={
                'db_table': 'articulo',
                'ordering': ['codigo_articulo'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lista_articulo', to='core.articulo')),
            ],
            options={
                'db_table': 'lista_precio',
                'ordering': ['articulo_id'],
            },
        ),
    ]
