# Generated by Django 5.2 on 2025-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articulo_listaprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
