# Generated by Django 5.2 on 2025-04-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_articulo_estado_remove_articulo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['articulo_id']},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='linea_id',
            new_name='linea',
        ),
    ]
