# Generated by Django 5.2 on 2025-04-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(max_length=250),
        ),
    ]
