# Generated by Django 5.2 on 2025-04-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_articulo_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
