# Generated by Django 5.2 on 2025-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_articulo_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='presentacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
