# Generated by Django 5.2 on 2025-05-06 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_articulo_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'canal_cliente',
                'ordering': ['canal_id'],
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('tipo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'tipo_identificacion',
                'ordering': ['tipo_id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['usuario_id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_identificacion', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('canal_id', models.ForeignKey(db_column='canal_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_canal', to='core.canalcliente')),
                ('tipo_id', models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='clientes', to='core.tipoidentificacion')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraCliente',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_pedido', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Completada'), (4, 'Cancelada')], default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.usuario')),
            ],
            options={
                'db_table': 'ordenes_compra_cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_pedido', to='core.cliente')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('articulo_id', models.ForeignKey(db_column='articulo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_articulo', to='core.articulo')),
                ('pedido_id', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_pedido', to='core.pedido')),
            ],
            options={
                'db_table': 'item_pedido',
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompraCliente',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_item', models.PositiveIntegerField(default=1)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_item_orden_compra', to='core.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden_compra', to='core.ordencompracliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.usuario')),
            ],
            options={
                'db_table': 'items_ordenes_compra_cliente',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_id', models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='vendedores', to='core.tipoidentificacion')),
            ],
            options={
                'db_table': 'vendedor',
                'ordering': ['vendedor_id'],
            },
        ),
        migrations.AddField(
            model_name='ordencompracliente',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.vendedor'),
        ),
    ]
